// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGldQTN3BRNREfYwRJWK3S7_JG1bz178',
    appId: '1:1080878765298:android:faaac39af98e2fc4ee6c6b',
    messagingSenderId: '1080878765298',
    projectId: 'fase-8-login',
    storageBucket: 'fase-8-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwob67cVjEpMi2OSyzFZsT7eJyo0o-7MM',
    appId: '1:1080878765298:ios:dd4e1538043c2ac2ee6c6b',
    messagingSenderId: '1080878765298',
    projectId: 'fase-8-login',
    storageBucket: 'fase-8-login.appspot.com',
    androidClientId: '1080878765298-14cj9cd3tf8bpunnvk2km6lmb8dkatde.apps.googleusercontent.com',
    iosClientId: '1080878765298-cpd2thpdit9k6gqbe2vr1mqmsjh10tmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLoginNotification',
  );
}
